# Generated by Django 5.2.4 on 2025-07-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_brutto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preis (Brutto)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preis (Netto)'),
        ),
    ]
