# Generated by Django 4.2.23 on 2025-07-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_price_brutto_product_price_netto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_brutto',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_netto',
        ),
    ]
